name: Continuous Deployment

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  Build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: login and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/kilimanjaro
            git pull origin dev
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh  
            npm install
            npm run build
            sudo kill -9 `sudo lsof -t -i:3000`
            pm2 start npm -- start
